### PR TITLE
nostr compatibility update

### PR DESCRIPTION
**Pull request by tannerdsilva**
Hi there - you had this on your radar for a while, and I apologize for taking so long in producing this.

Like I mentioned in the issue, I came into this project hot with assumptions and cheap fixes. Never claimed to have all the answers, but I did have some evidence that my quick changes increased the socket compatibility of this client greatly.

We both acknowledged that it wasn't strictly an RFC implementation issue, and its taken me some time to figure out exactly what is necessary and why. I dont want to change code just for the sake of changing it. This PR is where I've landed in taking accounts of everything in my project.

The most notable changes I've made in this PR is the significant reduction of the WebSocketInitialRequestHandler code, and moved much of it into a new HBWebSocketClientUpgrader.

The creation of the HBWebSocketClientUpgrader was absolutely critical here, because I have come to discover that SwiftNIO (when left to its default implementations) will send a client HTTP upgrade request with a `Connection:upgrade` header instead of `Connection:Upgrade`

RFC 6455 requires that sockets compare the value of this header case-insensitively, however, many sockets I've connected to seem to be doing a strict comparison with `Upgrade`.

The only way to have the "last word" in the headers that are sent in a web socket upgrade are to implement a custom `NIOHTTPClientProtocolUpgrader` compliant class. And this is what I've done.

### CODE REVIEW

**Comment by tannerdsilva** [comment]
I also greatly over estimated the quantity of websockets that were doing HTTP redirects.

Turns out, only one (prominent) host was doing this with their service, and they have since stopped.

My current implementation here (`HBWebSocketClientUpgrader`) will throw an appropriate error when a redirect is found, however, I have not merged this with the work you have done in your PR yet.

**Comment by tannerdsilva** [comment]
Wont build on my Mac without updating Package.swift to include the crypto library.

Have not tried Linux.

The code is error free.

**Comment by tannerdsilva** [comment]
I will submit one more commit to update tests if needed, I have not tried to build/run those (currently unclear how broken they are).

**Comment by adam-fowler** [comment]
Let me gets this right you are dragging in swift-crypto and Foundation to write a custom version of the WebSocket upgrade handler which changes `upgrade` to `Upgrade`. Have you thought of suggesting the one line change to swift-nio instead. Seems a more sensible solution.

**Comment by adam-fowler** [comment]
Oh also are you suggesting the redirect is no longer needed? If so I won't merge it as whatwg spec for web sockets says redirects should not be followed

**Comment by tannerdsilva** [comment]
I might be able to approach a change to SwiftNIO by simply adding a line [here](https://github.com/apple/swift-nio/blob/7a0ec436a1bee415826f67f5f678ceed00f383d0/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift#LL59C24-L59C24) instead of trying to modify the true source of the bad header value.

**Comment by tannerdsilva** [comment]
Bleh. I'm being reminded of this situation a bit better, having spent some time looking at NIO stuff again (its been many weeks).

I've decided I'm not interested in pursuing a change in SwiftNIO [here](https://github.com/apple/swift-nio/blob/7a0ec436a1bee415826f67f5f678ceed00f383d0/Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift#L188) because of previously mentioned reasons (not being WS specific code).

Furthermore, I dont think my theory on approaching NIO [here](https://github.com/apple/swift-nio/blob/7a0ec436a1bee415826f67f5f678ceed00f383d0/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift#LL59C24-L59C24) would be sane, because the inconsiderate forced addition of this upgrade value [here (the root issue)](https://github.com/apple/swift-nio/blob/7a0ec436a1bee415826f67f5f678ceed00f383d0/Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift#L188) means I would have a very messy logical situation to reverse [back here](https://github.com/apple/swift-nio/blob/7a0ec436a1bee415826f67f5f678ceed00f383d0/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift#LL59C24-L59C24).

## A note on headers

Part of the confusion I experienced in dealing with my issues initially was in carrying a bad assumption that I (the user of HBWebSocketClient) had full control over the headers. It wasn't until I began capturing socket data that I realized what the headers on the wire != my input headers. NIO injects its headers unconditionally, EVEN IF the user has applied their own value for that same key.

In my implementation, user input for headers are applied as the FINAL step before writing the HTTP request onto the socket. Nothing will override the user assigned values. The user has the final for each key.

`1.0.1` does not grant the same level of control over header output, and this was completely unclear to me until I put in some considerable debugging time.

## Next Steps

I need to look back at the NIO default websocket client upgrader and see how they used SHA1 without dependencies. If I can align my upgrader to look more like theirs (modified in my way), we can definitely drop the `Package.swift` commit.

Eliminating Foundation is straightforward and I will explore that next.

**Comment by adam-fowler** [comment]
Can you give me an example of websocket server that is not doing a case-insensitive check for the `connection: upgrade` header?

**Comment by tannerdsilva** [comment]
My needs continue to evolve - I feel it's probably best that I write my own NIO-based nostr library. Ideally I add an additional handler or two to the pipeline.

I'm still here to provide feedback in the context of your websocket project, if you have interest.

- The case issue with `Upgrade` is stupid and silly. I've been able to narrow this down to a single software project on the server side. The project is called `nerostr`, and the list of problematic URL's I've found (4 of them) are also the same 4 URL in the [paid relay section of this doc](https://github.com/hundehausen/monero-nostr-relays/blob/main/README.md). For my target audience, THIS IS A MASSIVE ISSUE. But these are LITERALLY the only 4 examples of this project in production. It is not hummingbirds fault this super-niche project isn't case insensitive.

- I am still under the belief it's a "better design" if your project is updated to apply headers the same way I've done it in this PR (create a dedicated protocol upgrader and modify the existing headers. Foundation and Crypto are obviously a problem, but in my `nostr-kit` library, I've proven that it can be implemented without either of these dependencies. [See this file in my lib](https://github.com/tannerdsilva/nostr-kit/blob/nostr-merge/Sources/nostr/Network/NIO/WebSockets/HTTP2WSUpgrade/RelayHTTPUpgrader.swift)

**Comment by adam-fowler** [comment]
I'm happy with what's in place. Sorry the websocket implementation didn't work for you. I hope you are able to submit a PR to fix the problematic server implementation.

**Pull request closed without merging**
