### PR TITLE
HBWebSocketClient responds to server redirects

### PR DESCRIPTION
**Pull request by adam-fowler**
Add support to HBWebSocketClient to respond to server redirects. Need to flag in config you want to follow redirects
```swift
let ws = try await HBWebSocketClient.connect(
    url: "ws://localhost:8080/test",
    configuration: .init(followRedirects: true),
    on: eventLoop
)
```

### CODE REVIEW

**Comment by tannerdsilva** [comment]
testing

**Comment by adam-fowler** [comment]
@tannerdsilva I'm planning to disallow redirects from removing TLS, as this is a security issue. Will this affect you?

**Comment by tannerdsilva** [comment]
I cant argue with your reasoning. Dont want to compromise on security.

**Comment by tannerdsilva** [comment]
I think we can close this one.

**Pull request closed without merging**
